export const ALL_STATES = [
  { state: 'Alabama', abbr: 'AL', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Birmingham_skyline_2016.jpg/800px-Birmingham_skyline_2016.jpg' },
  { state: 'Alaska', abbr: 'AK', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Anchorage%2C_Alaska_skyline.jpg/800px-Anchorage%2C_Alaska_skyline.jpg' },
  { state: 'Arizona', abbr: 'AZ', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Phoenix_skyline_from_South_Mountain_Park.jpg/800px-Phoenix_skyline_from_South_Mountain_Park.jpg' },
  { state: 'Arkansas', abbr: 'AR', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Little_Rock_skyline.jpg/800px-Little_Rock_skyline.jpg' },
  { state: 'California', abbr: 'CA', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/LA_Skyline_Mountains2.jpg/800px-LA_Skyline_Mountains2.jpg' },
  { state: 'Colorado', abbr: 'CO', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Denver_skyline_from_City_Park_%28cropped%29.jpg/800px-Denver_skyline_from_City_Park_%28cropped%29.jpg' },
  { state: 'Connecticut', abbr: 'CT', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Hartford%2C_CT_skyline_%28cropped%29.jpg/800px-Hartford%2C_CT_skyline_%28cropped%29.jpg' },
  { state: 'Delaware', abbr: 'DE', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Wilmington_Delaware_Skyline.jpg/800px-Wilmington_Delaware_Skyline.jpg' },
  { state: 'Florida', abbr: 'FL', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Downtown_Miami_skyline_from_Biscayne_Bay.jpg/800px-Downtown_Miami_skyline_from_Biscayne_Bay.jpg' },
  { state: 'Georgia', abbr: 'GA', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/A2ATL20250614-0721_%28cropped%29.jpg/800px-A2ATL20250614-0721_%28cropped%29.jpg' },
  { state: 'Hawaii', abbr: 'HI', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/2022_Views_from_Diamond_Head_02.jpg/800px-2022_Views_from_Diamond_Head_02.jpg' },
  { state: 'Idaho', abbr: 'ID', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Boise%2C_Idaho.jpg/800px-Boise%2C_Idaho.jpg' },
  { state: 'Illinois', abbr: 'IL', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Chicago_Skyline_Hi-Res.jpg/800px-Chicago_Skyline_Hi-Res.jpg' },
  { state: 'Indiana', abbr: 'IN', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Indianapolis_Skyline_from_I-70.jpg/800px-Indianapolis_Skyline_from_I-70.jpg' },
  { state: 'Iowa', abbr: 'IA', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Des_Moines_Iowa_skyline.jpg/800px-Des_Moines_Iowa_skyline.jpg' },
  { state: 'Kansas', abbr: 'KS', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Wichita_Skyline.jpg/800px-Wichita_Skyline.jpg' },
  { state: 'Kentucky', abbr: 'KY', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Louisville_Skyline_-_Feb_2019.jpg/800px-Louisville_Skyline_-_Feb_2019.jpg' },
  { state: 'Louisiana', abbr: 'LA', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/New_Orleans_Skyline_from_Algiers_Point.jpg/800px-New_Orleans_Skyline_from_Algiers_Point.jpg' },
  { state: 'Maine', abbr: 'ME', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Portland_Maine_Skyline.jpg/800px-Portland_Maine_Skyline.jpg' },
  { state: 'Maryland', abbr: 'MD', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Baltimore_Inner_Harbor_skyline_2019.jpg/800px-Baltimore_Inner_Harbor_skyline_2019.jpg' },
  { state: 'Massachusetts', abbr: 'MA', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Boston_skyline_from_Fan_Pier.jpg/800px-Boston_skyline_from_Fan_Pier.jpg' },
  { state: 'Michigan', abbr: 'MI', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Detroit_Skyline_from_Windsor.jpg/800px-Detroit_Skyline_from_Windsor.jpg' },
  { state: 'Minnesota', abbr: 'MN', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Minneapolis_Skyline_2019.jpg/800px-Minneapolis_Skyline_2019.jpg' },
  { state: 'Mississippi', abbr: 'MS', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Downtown_Jackson_Mississippi.jpg/800px-Downtown_Jackson_Mississippi.jpg' },
  { state: 'Missouri', abbr: 'MO', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Kansas_City_Missouri_Skyline.jpg/800px-Kansas_City_Missouri_Skyline.jpg' },
  { state: 'Montana', abbr: 'MT', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Billings_Skyline_from_the_Rims.jpg/800px-Billings_Skyline_from_the_Rims.jpg' },
  { state: 'Nebraska', abbr: 'NE', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Omaha_skyline.jpg/800px-Omaha_skyline.jpg' },
  { state: 'Nevada', abbr: 'NV', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Las_Vegas_Strip_Panorama.jpg/800px-Las_Vegas_Strip_Panorama.jpg' },
  { state: 'New Hampshire', abbr: 'NH', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Manchester_New_Hampshire_skyline.jpg/800px-Manchester_New_Hampshire_skyline.jpg' },
  { state: 'New Jersey', abbr: 'NJ', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Newark_NJ_Skyline_2013.jpg/800px-Newark_NJ_Skyline_2013.jpg' },
  { state: 'New Mexico', abbr: 'NM', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Albuquerque_New_Mexico_Skyline_2.jpg/800px-Albuquerque_New_Mexico_Skyline_2.jpg' },
  { state: 'New York', abbr: 'NY', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Midtown_Manhattan_skyline_from_Hoboken.jpg/800px-Midtown_Manhattan_skyline_from_Hoboken.jpg' },
  { state: 'North Carolina', abbr: 'NC', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Charlotte_Skyline_2019.jpg/800px-Charlotte_Skyline_2019.jpg' },
  { state: 'North Dakota', abbr: 'ND', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Fargo_Skyline.jpg/800px-Fargo_Skyline.jpg' },
  { state: 'Ohio', abbr: 'OH', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Columbus_Ohio_Skyline_2019.jpg/800px-Columbus_Ohio_Skyline_2019.jpg' },
  { state: 'Oklahoma', abbr: 'OK', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Oklahoma_City_Skyline_2020.jpg/800px-Oklahoma_City_Skyline_2020.jpg' },
  { state: 'Oregon', abbr: 'OR', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Portland_Oregon_Skyline_from_Pittock_Mansion.jpg/800px-Portland_Oregon_Skyline_from_Pittock_Mansion.jpg' },
  { state: 'Pennsylvania', abbr: 'PA', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Philadelphia_skyline_from_South_Street_Bridge.jpg/800px-Philadelphia_skyline_from_South_Street_Bridge.jpg' },
  { state: 'Rhode Island', abbr: 'RI', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Providence_Skyline_from_Prospect_Terrace_Park.jpg/800px-Providence_Skyline_from_Prospect_Terrace_Park.jpg' },
  { state: 'South Carolina', abbr: 'SC', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Charleston_SC_Skyline.jpg/800px-Charleston_SC_Skyline.jpg' },
  { state: 'South Dakota', abbr: 'SD', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Sioux_Falls_skyline_2015.jpg/800px-Sioux_Falls_skyline_2015.jpg' },
  { state: 'Tennessee', abbr: 'TN', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Nashville_Skyline_from_Shelby_Street_Bridge.jpg/800px-Nashville_Skyline_from_Shelby_Street_Bridge.jpg' },
  { state: 'Texas', abbr: 'TX', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Austin_Texas_Skyline_2018.jpg/800px-Austin_Texas_Skyline_2018.jpg' },
  { state: 'Utah', abbr: 'UT', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Salt_Lake_City_Skyline_from_Ensign_Peak.jpg/800px-Salt_Lake_City_Skyline_from_Ensign_Peak.jpg' },
  { state: 'Vermont', abbr: 'VT', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Burlington_Vermont_Skyline.jpg/800px-Burlington_Vermont_Skyline.jpg' },
  { state: 'Virginia', abbr: 'VA', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Richmond_Virginia_Skyline.jpg/800px-Richmond_Virginia_Skyline.jpg' },
  { state: 'Washington', abbr: 'WA', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Seattle_skyline_from_Kerry_Park.jpg/800px-Seattle_skyline_from_Kerry_Park.jpg' },
  { state: 'West Virginia', abbr: 'WV', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Charleston_West_Virginia_Skyline.jpg/800px-Charleston_West_Virginia_Skyline.jpg' },
  { state: 'Wisconsin', abbr: 'WI', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Milwaukee_Skyline_from_Lake_Michigan.jpg/800px-Milwaukee_Skyline_from_Lake_Michigan.jpg' },
  { state: 'Wyoming', abbr: 'WY', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Cheyenne_Wyoming_Skyline.jpg/800px-Cheyenne_Wyoming_Skyline.jpg' },
];
