export const ALL_STATES = [
    { state: "Alabama", abbr: "AL", img: "https://upload.wikimedia.org/wikipedia/commons/1/17/Birmingham%2C_Alabama.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "Alaska", abbr: "AK", img: "https://upload.wikimedia.org/wikipedia/commons/b/be/Anchorage%2C_Alaska_skyline.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "Arizona", abbr: "AZ", img: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Downtown_Phoenix_Aerial_Looking_Northeast.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "Arkansas", abbr: "AR", img: "https://upload.wikimedia.org/wikipedia/commons/3/3d/William_J._Clinton_Presidential_Library%2C_Little_Rock%2C_Arkansas_LCCN2011633870.tif?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "California", abbr: "CA", img: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Hollywood_sign_%288485145044%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "Colorado", abbr: "CO", img: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Denver%2C_Colorado_skyline_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "Connecticut", abbr: "CT", img: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Hartford%2C_CT_skyline_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "Delaware", abbr: "DE", img: "https://upload.wikimedia.org/wikipedia/commons/6/61/Wilmington%2C_Delaware%2C_USA.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "Florida", abbr: "FL", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Georgia", abbr: "GA", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Hawaii", abbr: "HI", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Idaho", abbr: "ID", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Illinois", abbr: "IL", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Indiana", abbr: "IN", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Iowa", abbr: "IA", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Kansas", abbr: "KS", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Kentucky", abbr: "KY", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Louisiana", abbr: "LA", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Maine", abbr: "ME", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Maryland", abbr: "MD", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Massachusetts", abbr: "MA", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Michigan", abbr: "MI", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Minnesota", abbr: "MN", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Mississippi", abbr: "MS", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Missouri", abbr: "MO", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Montana", abbr: "MT", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Nebraska", abbr: "NE", img: "https://upload.wikimedia.org/wikipedia/commons/b/b6/City_of_Omaha%2C_Nebraska_Skyline_on_the_Missouri_River_%2830899969517%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "Nevada", abbr: "NV", img: "https://upload.wikimedia.org/wikipedia/commons/d/da/Las_Vegas_from_above_%2840064746644%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "New Hampshire", abbr: "NH", img: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Manchester%2C_New_Hampshire_skyline.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "New Jersey", abbr: "NJ", img: "https://upload.wikimedia.org/wikipedia/commons/d/d7/2025-09-12_12_24_59_Aerial_view_of_downtown_in_Newark%2C_Essex_County%2C_New_Jersey_from_an_aircraft_which_just_departed_from_Newark_Liberty_International_Airport.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "New Mexico", abbr: "NM", img: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Albuquerque%2C_New_Mexico_skyline.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "New York", abbr: "NY", img: "https://upload.wikimedia.org/wikipedia/commons/7/7a/View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "North Carolina", abbr: "NC", img: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Uptown_Charlotte_2018_taking_by_DJI_Phantom_4_pro.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "North Dakota", abbr: "ND", img: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Downtown_Fargo_Aerial_-_Facing_Southeast_%2851009704407%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "Ohio", abbr: "OH", img: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Downtown_Columbus_View_from_Main_St_Bridge_-_edit1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "Oklahoma", abbr: "OK", img: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Oklahoma_city_downtown.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original" },
    { state: "Oregon", abbr: "OR", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Pennsylvania", abbr: "PA", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Rhode Island", abbr: "RI", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "South Carolina", abbr: "SC", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "South Dakota", abbr: "SD", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Tennessee", abbr: "TN", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Texas", abbr: "TX", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Utah", abbr: "UT", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Vermont", abbr: "VT", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Virginia", abbr: "VA", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Washington", abbr: "WA", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "West Virginia", abbr: "WV", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Wisconsin", abbr: "WI", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" },
    { state: "Wyoming", abbr: "WY", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/US_flag_48_stars.svg/1024px-US_flag_48_stars.svg.png" }
];