export const ALL_STATES = [
    { state: "Alabama", abbr: "AL", img: "/static/images/icons/commonswiki.svg" },
    { state: "Alaska", abbr: "AK", img: "/static/images/icons/commonswiki.svg" },
    { state: "Arizona", abbr: "AZ", img: "/static/images/icons/commonswiki.svg" },
    { state: "Arkansas", abbr: "AR", img: "/static/images/icons/commonswiki.svg" },
    { state: "California", abbr: "CA", img: "/static/images/icons/commonswiki.svg" },
    { state: "Colorado", abbr: "CO", img: "/static/images/icons/commonswiki.svg" },
    { state: "Connecticut", abbr: "CT", img: "/static/images/icons/commonswiki.svg" },
    { state: "Delaware", abbr: "DE", img: "/static/images/icons/commonswiki.svg" },
    { state: "Florida", abbr: "FL", img: "/static/images/icons/commonswiki.svg" },
    { state: "Georgia", abbr: "GA", img: "/static/images/icons/commonswiki.svg" },
    { state: "Hawaii", abbr: "HI", img: "/static/images/icons/commonswiki.svg" },
    { state: "Idaho", abbr: "ID", img: "/static/images/icons/commonswiki.svg" },
    { state: "Illinois", abbr: "IL", img: "/static/images/icons/commonswiki.svg" },
    { state: "Indiana", abbr: "IN", img: "/static/images/icons/commonswiki.svg" },
    { state: "Iowa", abbr: "IA", img: "/static/images/icons/commonswiki.svg" },
    { state: "Kansas", abbr: "KS", img: "/static/images/icons/commonswiki.svg" },
    { state: "Kentucky", abbr: "KY", img: "/static/images/icons/commonswiki.svg" },
    { state: "Louisiana", abbr: "LA", img: "/static/images/icons/commonswiki.svg" },
    { state: "Maine", abbr: "ME", img: "/static/images/icons/commonswiki.svg" },
    { state: "Maryland", abbr: "MD", img: "/static/images/icons/commonswiki.svg" },
    { state: "Massachusetts", abbr: "MA", img: "/static/images/icons/commonswiki.svg" },
    { state: "Michigan", abbr: "MI", img: "/static/images/icons/commonswiki.svg" },
    { state: "Minnesota", abbr: "MN", img: "/static/images/icons/commonswiki.svg" },
    { state: "Mississippi", abbr: "MS", img: "/static/images/icons/commonswiki.svg" },
    { state: "Missouri", abbr: "MO", img: "/static/images/icons/commonswiki.svg" },
    { state: "Montana", abbr: "MT", img: "/static/images/icons/commonswiki.svg" },
    { state: "Nebraska", abbr: "NE", img: "/static/images/icons/commonswiki.svg" },
    { state: "Nevada", abbr: "NV", img: "/static/images/icons/commonswiki.svg" },
    { state: "New Hampshire", abbr: "NH", img: "/static/images/icons/commonswiki.svg" },
    { state: "New Jersey", abbr: "NJ", img: "/static/images/icons/commonswiki.svg" },
    { state: "New Mexico", abbr: "NM", img: "/static/images/icons/commonswiki.svg" },
    { state: "New York", abbr: "NY", img: "/static/images/icons/commonswiki.svg" },
    { state: "North Carolina", abbr: "NC", img: "/static/images/icons/commonswiki.svg" },
    { state: "North Dakota", abbr: "ND", img: "/static/images/icons/commonswiki.svg" },
    { state: "Ohio", abbr: "OH", img: "/static/images/icons/commonswiki.svg" },
    { state: "Oklahoma", abbr: "OK", img: "/static/images/icons/commonswiki.svg" },
    { state: "Oregon", abbr: "OR", img: "/static/images/icons/commonswiki.svg" },
    { state: "Pennsylvania", abbr: "PA", img: "/static/images/icons/commonswiki.svg" },
    { state: "Rhode Island", abbr: "RI", img: "/static/images/icons/commonswiki.svg" },
    { state: "South Carolina", abbr: "SC", img: "/static/images/icons/commonswiki.svg" },
    { state: "South Dakota", abbr: "SD", img: "/static/images/icons/commonswiki.svg" },
    { state: "Tennessee", abbr: "TN", img: "/static/images/icons/commonswiki.svg" },
    { state: "Texas", abbr: "TX", img: "/static/images/icons/commonswiki.svg" },
    { state: "Utah", abbr: "UT", img: "/static/images/icons/commonswiki.svg" },
    { state: "Vermont", abbr: "VT", img: "/static/images/icons/commonswiki.svg" },
    { state: "Virginia", abbr: "VA", img: "/static/images/icons/commonswiki.svg" },
    { state: "Washington", abbr: "WA", img: "/static/images/icons/commonswiki.svg" },
    { state: "West Virginia", abbr: "WV", img: "/static/images/icons/commonswiki.svg" },
    { state: "Wisconsin", abbr: "WI", img: "/static/images/icons/commonswiki.svg" },
    { state: "Wyoming", abbr: "WY", img: "/static/images/icons/commonswiki.svg" }
];