"""
Declarative Visual Scene-Graph Compiler & Two-Way Transpiler.
Compiles SceneGraph JSON trees into Next.js React JSX / HTML5 and generates scenes from data.
"""

from typing import Dict, List, Any, Optional
from core.visual.models import (
    NodeType,
    LayoutConfig,
    StyleConfig,
    ResponsiveConfig,
    SceneNode,
    SceneGraph,
)


class SceneGraphCompiler:
    """
    Two-way transpiler between SceneGraph AST, Production Code (JSX/HTML), and Structured State.
    """

    @classmethod
    def to_jsx(cls, scene_graph: SceneGraph, component_name: str = "GeneratedVisualView") -> str:
        """Transpiles a SceneGraph AST into a clean Next.js React JSX component."""
        rendered_root = cls._render_node_jsx(scene_graph.root_node, depth=1)
        
        jsx_code = f"""'use client';

import React from 'react';

/**
 * {scene_graph.title}
 * Auto-generated by Omniverse Scene-Graph Compiler.
 */
export function {component_name}() {{
  return (
{rendered_root}
  );
}}

export default {component_name};
"""
        return jsx_code

    @classmethod
    def _render_node_jsx(cls, node: SceneNode, depth: int = 1) -> str:
        """Recursively renders a SceneNode into JSX."""
        indent = "  " * depth
        child_indent = "  " * (depth + 1)
        
        # Build Tailwind & Atomic CSS classes
        classes: List[str] = []
        if node.style.custom_classes:
            classes.extend(node.style.custom_classes)

        # Layout mapping
        if node.layout.display == "flex":
            classes.append("flex")
            if node.layout.direction == "column":
                classes.append("flex-col")
            if node.layout.justify == "center":
                classes.append("justify-center")
            elif node.layout.justify == "between":
                classes.append("justify-between")
            if node.layout.align == "center":
                classes.append("items-center")
        elif node.layout.display == "grid":
            classes.append("grid")
            cols = node.layout.columns
            classes.append(f"grid-cols-1 md:grid-cols-{min(cols, 4)}")

        # Style tokens
        if node.node_type == NodeType.CARD:
            classes.extend(["bg-white", "rounded-2xl", "shadow-sm", "border", "border-slate-100", "p-6"])
        elif node.node_type == NodeType.BADGE:
            classes.extend(["inline-flex", "items-center", "px-3", "py-1", "rounded-full", "text-xs", "font-semibold", "bg-amber-100", "text-amber-900"])
        elif node.node_type == NodeType.BUTTON:
            classes.extend(["inline-flex", "items-center", "justify-center", "px-6", "py-3", "rounded-xl", "font-bold", "bg-[#0A2540]", "text-white", "hover:bg-[#1E3A8A]", "transition-colors", "cursor-pointer"])
        elif node.node_type == NodeType.FORM_INPUT:
            classes.extend(["w-full", "px-4", "py-3", "rounded-xl", "border", "border-slate-200", "focus:ring-2", "focus:ring-blue-500", "outline-none", "select-text"])
        elif node.node_type == NodeType.METRIC_CARD:
            classes.extend(["p-4", "rounded-xl", "bg-slate-50", "border", "border-slate-200/60"])

        # Non-copyable constraint
        if node.node_type != NodeType.FORM_INPUT:
            classes.append("select-none")

        class_str = f' className="{" ".join(classes)}"' if classes else ""
        elem_id = f' id="{node.id}"' if node.id else ""

        # Node type tag mapping
        tag_map = {
            NodeType.CONTAINER: "div",
            NodeType.CARD: "div",
            NodeType.GRID: "div",
            NodeType.TEXT: "p",
            NodeType.BUTTON: "button",
            NodeType.BADGE: "span",
            NodeType.IMAGE: "img",
            NodeType.FORM_INPUT: "input",
            NodeType.METRIC_CARD: "div",
        }
        tag = tag_map.get(node.node_type, "div")

        # Self-closing tags (e.g. input, img)
        if node.node_type == NodeType.FORM_INPUT:
            placeholder = node.attributes.get("placeholder", "")
            return f'{indent}<input{elem_id}{class_str} type="text" placeholder="{placeholder}" />'
        elif node.node_type == NodeType.IMAGE:
            src = node.attributes.get("src", "/assets/images/hero.webp")
            alt = node.attributes.get("alt", "Visual Asset")
            return f'{indent}<img{elem_id}{class_str} src="{src}" alt="{alt}" loading="lazy" />'

        # Text or Container with children
        if not node.children:
            text_content = node.content or ""
            return f"{indent}<{tag}{elem_id}{class_str}>{text_content}</{tag}>"

        children_jsx = "\n".join(cls._render_node_jsx(child, depth + 1) for child in node.children)
        return f"{indent}<{tag}{elem_id}{class_str}>\n{children_jsx}\n{indent}</{tag}>"

    @classmethod
    def to_html(cls, scene_graph: SceneGraph) -> str:
        """Compiles SceneGraph into semantic HTML5 string."""
        jsx_str = cls.to_jsx(scene_graph, component_name="Component")
        # Lightweight clean HTML extraction
        return f'<div class="scene-graph-root" data-graph-id="{scene_graph.graph_id}">\n' + jsx_str + '\n</div>'

    @classmethod
    def from_data(cls, data_type: str, payload: Dict[str, Any]) -> SceneGraph:
        """
        Dynamically synthesizes a complete SceneGraph tree from structured domain data.
        """
        graph = SceneGraph(
            title=payload.get("title", f"Dynamic {data_type.title()} View"),
            meta={"source_type": data_type}
        )

        root = SceneNode(
            node_type=NodeType.CONTAINER,
            name="MainWrapper",
            layout=LayoutConfig(display="flex", direction="column", gap="1.5rem", padding="2rem"),
            style=StyleConfig(background="#F8FAFC")
        )

        # Header Section
        header_card = SceneNode(
            node_type=NodeType.CARD,
            name="HeaderBanner",
            layout=LayoutConfig(display="flex", direction="row", justify="between", align="center"),
            style=StyleConfig(background="#FFFFFF")
        )
        title_node = SceneNode(
            node_type=NodeType.TEXT,
            name="TitleText",
            content=payload.get("headline", payload.get("title", "Campaign Dashboard")),
            style=StyleConfig(font_size="1.75rem", font_weight="700", color="#0A2540")
        )
        badge_node = SceneNode(
            node_type=NodeType.BADGE,
            name="StatusBadge",
            content=payload.get("badge_text", "VERIFIED LIVE")
        )
        header_card.add_child(title_node).add_child(badge_node)
        root.add_child(header_card)

        # Metrics Grid Section
        metrics = payload.get("metrics", {})
        if metrics:
            grid_node = SceneNode(
                node_type=NodeType.GRID,
                name="MetricsGrid",
                layout=LayoutConfig(display="grid", columns=len(metrics), gap="1rem")
            )
            for k, v in metrics.items():
                m_card = SceneNode(
                    node_type=NodeType.METRIC_CARD,
                    name=f"Metric_{k}",
                    layout=LayoutConfig(display="flex", direction="column", gap="0.25rem")
                )
                m_label = SceneNode(node_type=NodeType.TEXT, content=k.replace("_", " ").title(), style=StyleConfig(font_size="0.875rem", color="#64748B"))
                m_val = SceneNode(node_type=NodeType.TEXT, content=str(v), style=StyleConfig(font_size="1.5rem", font_weight="700", color="#0A2540"))
                m_card.add_child(m_label).add_child(m_val)
                grid_node.add_child(m_card)
            root.add_child(grid_node)

        # CTA / Action Section
        if "cta_text" in payload:
            cta_button = SceneNode(
                node_type=NodeType.BUTTON,
                name="PrimaryCTA",
                content=payload["cta_text"],
                attributes={"data-cta-target": payload.get("target_corridor", "50-States")}
            )
            root.add_child(cta_button)

        graph.root_node = root
        return graph
