"""
Typed Event Models for the Omniverse Publish-Subscribe Message Pool.
"""

import uuid
from datetime import datetime
from typing import Dict, List, Optional, Any, Set, Union
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# 1. Domain Event Payloads
# ---------------------------------------------------------------------------

class RequirementDoc(BaseModel):
    """Product / Growth Requirement Document (PRD)."""
    prd_id: str = Field(default_factory=lambda: f"PRD-{uuid.uuid4().hex[:8].upper()}")
    title: str
    business_goal: str
    target_audience: str = "Auto Transport Shippers"
    target_corridors: List[str] = Field(default_factory=list)
    user_stories: List[str] = Field(default_factory=list)
    target_kpi: str = "Conversion rate lift and sub-2.5s render speed"
    priority: str = "HIGH"
    author_agent_id: str = "growth_meta_buyer"


class ArchitectureSpec(BaseModel):
    """System Architecture Specification from Principal Architects."""
    spec_id: str = Field(default_factory=lambda: f"ARCH-{uuid.uuid4().hex[:8].upper()}")
    prd_ref: str
    system_name: str
    components_affected: List[str] = Field(default_factory=list)
    data_flow: List[str] = Field(default_factory=list)
    security_considerations: List[str] = Field(default_factory=list)
    performance_budget_ms: float = 100.0
    author_agent_id: str = "web_frontend_julian_thorne"


class TaskTicket(BaseModel):
    """Discrete atomic task ticket assigned to specialist agents."""
    ticket_id: str = Field(default_factory=lambda: f"TASK-{uuid.uuid4().hex[:8].upper()}")
    title: str
    assigned_agent_id: str
    assigned_pod: str
    dependencies: List[str] = Field(default_factory=list)
    action_items: List[str] = Field(default_factory=list)
    status: str = "PENDING"  # PENDING, IN_PROGRESS, COMPLETED, BLOCKED


class CodeDiff(BaseModel):
    """Code change payload generated by Engineering."""
    diff_id: str = Field(default_factory=lambda: f"DIFF-{uuid.uuid4().hex[:8].upper()}")
    task_id: str
    file_path: str
    action: str = "MODIFY"  # MODIFY, CREATE, DELETE
    code_content: str
    language: str = "javascript"
    author_agent_id: str = "web_frontend_julian_thorne"
    commit_message: str


class VerificationResult(BaseModel):
    """Verification and quality audit report from Reviewer agents."""
    audit_id: str = Field(default_factory=lambda: f"AUDIT-{uuid.uuid4().hex[:8].upper()}")
    target_ref_id: str  # task_id or diff_id
    reviewer_agent_id: str
    status: str = "VERIFIED"  # VERIFIED, REJECTED, CHANGES_REQUESTED
    checklist_passed: Dict[str, bool] = Field(default_factory=dict)
    unresolved_defects: List[str] = Field(default_factory=list)
    rationale: str = ""
    signoff_token: Optional[str] = None


class DeploymentManifest(BaseModel):
    """Production deployment instructions and telemetry receipt."""
    manifest_id: str = Field(default_factory=lambda: f"DEP-{uuid.uuid4().hex[:8].upper()}")
    build_version: str
    environment: str = "production"
    files_synced: List[str] = Field(default_factory=list)
    cache_purged: bool = True
    domain: str = "https://www.skyautoservices.com"
    dri_agent_id: str = "web_devops_marcus_chen"
    deployed_at: datetime = Field(default_factory=datetime.utcnow)


class InfrastructureAlert(BaseModel):
    """Real-time operational anomaly or SRE alert."""
    alert_id: str = Field(default_factory=lambda: f"ALT-{uuid.uuid4().hex[:8].upper()}")
    severity: str = "CRITICAL"  # INFO, WARNING, CRITICAL
    subsystem: str
    error_message: str
    telemetry_snapshot: Dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# 2. Master Event Envelope
# ---------------------------------------------------------------------------

class EventMessage(BaseModel):
    """Standard envelope wrapping all typed domain messages on the bus."""
    message_id: str = Field(default_factory=lambda: f"msg_{uuid.uuid4().hex[:12]}")
    topic: str  # e.g. "product.prd", "engineering.spec", "qa.verification", "devops.deploy"
    tags: Set[str] = Field(default_factory=set)  # e.g. {"frontend", "devops", "qa", "growth"}
    sender_id: str
    target_agent_id: Optional[str] = None  # None = broadcast to all topic/tag subscribers
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    payload_type: str
    payload: Dict[str, Any] = Field(default_factory=dict)

    @classmethod
    def create(cls, topic: str, sender_id: str, payload_obj: BaseModel, tags: Optional[Set[str]] = None, target_agent: Optional[str] = None) -> "EventMessage":
        payload_data = payload_obj.model_dump() if hasattr(payload_obj, "model_dump") else payload_obj.dict()
        inferred_tags = set(tags or set())
        inferred_tags.add(topic.split(".")[0])
        return cls(
            topic=topic,
            tags=inferred_tags,
            sender_id=sender_id,
            target_agent_id=target_agent,
            payload_type=type(payload_obj).__name__,
            payload=payload_data
        )
