"""
Data models for Epigenetic Prompt Evolution and Reflexion loops.
"""

import uuid
from datetime import datetime
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field


class HeuristicRule(BaseModel):
    """An atomic learned operational rule or constraint for an agent persona."""
    rule_id: str = Field(default_factory=lambda: f"HR-{uuid.uuid4().hex[:8].upper()}")
    category: str = "general"  # syntax, security, a11y, layout, anti_drift, efficiency
    rule_text: str
    rationale: str
    source_ticket_id: str
    severity: str = "MUST"  # MUST, SHOULD, AVOID
    is_active: bool = True
    effectiveness_score: float = 1.0
    created_at: datetime = Field(default_factory=datetime.utcnow)


class ReflexionReport(BaseModel):
    """Post-execution reflective critique generated by HR / Quality Pod."""
    report_id: str = Field(default_factory=lambda: f"REF-{uuid.uuid4().hex[:8].upper()}")
    ticket_id: str
    agent_id: str
    success: bool
    identified_failure_mode: Optional[str] = None
    critique: str
    proposed_rule: Optional[HeuristicRule] = None
    evaluated_by: str = "hr_director_chloe_williams"
    created_at: datetime = Field(default_factory=datetime.utcnow)


class PromptVersion(BaseModel):
    """Snapshot of an agent's prompt heuristics at a given revision."""
    version_id: str = Field(default_factory=lambda: f"v_{uuid.uuid4().hex[:8]}")
    agent_id: str
    version_number: int
    active_rules: List[HeuristicRule] = Field(default_factory=list)
    success_rate: float = 1.0
    created_at: datetime = Field(default_factory=datetime.utcnow)
